# Breathing techniques of the Wim Hof Method
# For more information, please visit:
#     https://www.wimhofmethod.com/breathing-techniques

theme: "themes/default.yaml"
breathing: "presets/wimhof.yaml"
